/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTEInterface: ThisInterface class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * DoInterface not edit the class manually.
 */
import { MoneyInterface } from './money';


export interface BudgetedAtMonthInterface { 
    id?: number;
    money?: MoneyInterface;
}
