/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTEInterface: ThisInterface class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * DoInterface not edit the class manually.
 */
import { BudgetedAtMonthInterface } from './budgetedAtMonth';
import { CategoryInterface } from './category';


export interface CategoriesView { 
    defaultCategory?: CategoryInterface;
    defaultCategoryBudgetedAtMonth?: BudgetedAtMonthInterface;
    categories?: Array<CategoryInterface>;
    categoryBudgetedAtMonths?: Array<BudgetedAtMonthInterface>;
}
