/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTEInterface: ThisInterface class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * DoInterface not edit the class manually.
 */


export interface MoneyInterface { 
    amount?: string;
    currency?: string;
}
