/**
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: ThisInterface class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * DoInterface not edit the class manually.
 */


export interface UserInterface { 
    id?: number;
    email?: string;
}
